### ISSUE TITLE
Check How Long Running DR Twice Actually Takes

### ISSUE THREAD

**Issue by dally96** [dally96/cmssw#4]
Check the condor log files to see the time it took to run.

**Comment by dally96** [comment]
Max runtime of 6 bins running once: 784 s
Max runtime of 6 bins running twice (before improving the code): 1116 s

**Comment by trholmes** [comment]
Interesting! Did you get a sense if the mean changed too?

**Comment by dally96** [comment]
When I looked at 6 bins, it seems the mean increased by a few hundred seconds. However, after I improved the code, it looks like the mean time it took to run decreased, for 6 bins at least. It probably does depend on how many jobs are currently running on the cluster since some jobs do take 20 minutes to run others take 10 minutes.

**Comment by trholmes** [comment]
OK makes sense, so nothing significant then. I bet it's just fluctuations but we should keep an eye on it.
